### ISSUE TITLE
Deprecated libraries 

### ISSUE THREAD

**Issue by vishnusureshperumbavoor** [premthomas/Ollama-and-Agents#1]
"from langchain.llms import Ollama" is now "from langchain_community.llms import Ollama"

"from langchain.tools import DuckDuckGoSearchRun" is now "from langchain_community.tools import DuckDuckGoSearchRun"

need one more parameter "expected_ouput=" in Task function

**Comment by TomWest61** [comment]
You need to add at the tasks:
expected_output="What ever you want",

Try:

# Define your tasks with their specific descriptions and expected outputs
task1 = Task(
  description="Research about open source LLMs vs closed source LLMs. Your final answer MUST be a full analysis report.",
  expected_output="A detailed report on open source LLMs vs closed source LLMs.",
  agent=researcher
)

task2 = Task(
  description="Using the insights provided, develop an engaging blog post that highlights the most significant facts and differences between open-source LLMs and closed-source LLMs. Your post should be informative yet accessible, catering to a tech-savvy audience. Make it sound cool, and avoid complex words so it doesn't sound like AI. Your final answer MUST be the full blog post of at least 4 paragraphs. The target word count for the blog post should be between 1,500 and 2,500 words, with a sweet spot at around 2,450 words.",
  expected_output="A blog post of at least 4 paragraphs highlighting the most significant facts and differences between open-source LLMs and closed-source LLMs.",
  agent=writer
)

**Comment by premthomas** [comment]
Thank you @vishnusureshperumbavoor  and @TomWest61. I have updated the code.
