### ISSUE TITLE
Ollama is now available for Windows

### ISSUE THREAD

**Issue by movAX13h** [premthomas/Ollama-and-Agents#2]
Ollama is now available for Windows. WSL is not needed.
https://github.com/ollama/ollama?tab=readme-ov-file#windows-preview

**Comment by premthomas** [comment]
Thank you @movAX13h. Yes, this blog was written when Windows was not available. I am also writing this to introduce some of my colleagues to Linux as we have been life-long users of Windows. This is mostly to show users that Linux need not be as scary!
